#!/usr/bin/env python3
"""
ArchiLudo sprite export-for-editing
======================================

Summary: Exports every sprite this project currently ships (the four
pawn colours, generate_icon_sprites.py; the four app-icon size/aspect
variants, generate_app_icon.py) as plain PNGs into assets/edit/, for
hand pixel-correction in an external image editor (e.g. Photoshop) --
per explicit user request ("save PNG versions... so i can try to pixel
correct them"). See assets/import_edited_sprites.py to convert whatever
ends up in assets/edit/ back into the real packed RISC OS sprite files
(PawnSprites/!Sprites/!Sprites22) -- the two scripts are a matched
pair, see that one's own doc comment for the round-trip.

Why PNG, not PSD: Pillow (the only image library available in this
project's tooling) can only READ PSD files, not write them, and there's
no reliable pure-Python PSD writer to reach for instead. This isn't
much of a loss for sprites like these anyway -- each one is already a
single flat layer (solid colour regions + a hard alpha mask, no blend
modes/effects/multiple layers to preserve), which is exactly what PNG
represents natively. PNG is also the normal working format for pixel
art at this scale in practice, not a compromise.

Two files per sprite:
- `<name>.png` -- exactly the current native resolution (e.g. 26x26
  for a pawn) -- useful as a reference, but impractically small to
  comfortably click individual pixels in most editors.
- `<name>_16x.png` -- the same image scaled up 16x with NEAREST
  (no blending -- every source pixel becomes a clean 16x16 block, so
  the *editing* grid exactly matches the *sprite* grid). Edit THIS one:
  zoom to 100% in your editor, use a 1px hard-edged pencil (never a
  soft/anti-aliased brush), and every stroke will land exactly on
  sprite pixel boundaries when scaled back down.

Syntax:  python3 assets/export_sprites_for_editing.py
Output:  assets/edit/*.png (native + _16x per sprite), assets/edit/README.md
"""

import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
EDIT_DIR = HERE / "edit"

UPSCALE = 16

# (native PNG source, edit/ basename)
SPRITE_SOURCES = [
    (HERE / "pawn_icon0.png", "pawn0"),
    (HERE / "pawn_icon1.png", "pawn1"),
    (HERE / "pawn_icon2.png", "pawn2"),
    (HERE / "pawn_icon3.png", "pawn3"),
    (HERE / "app_icon_full.png", "archiludo_full_sq"),
    (HERE / "app_icon_half.png", "archiludo_half_sq"),
    (HERE / "app_icon_full_rect.png", "archiludo_full_rect"),
    (HERE / "app_icon_half_rect.png", "archiludo_half_rect"),
]

README = """\
# ArchiLudo sprite pixel-editing workspace

Generated by `assets/export_sprites_for_editing.py` -- DO NOT hand-edit
`pawn0.png`/`archiludo_full_sq.png`/etc. (the plain, native-resolution
copies) directly; they're far too small to click individual pixels
accurately in most editors. Edit the `_16x.png` versions instead, then
run `assets/import_edited_sprites.py` to convert your edits back into
the real sprite files ArchiLudo actually ships.

## Workflow

1. Open a `*_16x.png` file (e.g. `pawn0_16x.png`) in your image editor.
   Every sprite pixel is already a clean 16x16 block -- zoom to 100% and
   you'll see it as a perfect pixel grid.
2. Edit using a **1px hard-edged pencil tool only** -- never a soft or
   anti-aliased brush, and never resize/rotate/apply filters. Keep every
   edit's edges snapped to the existing 16x16 block boundaries. Colours
   don't need to be exact matches to the originals -- the import step
   re-quantises everything against RISC OS's fixed 16-colour Wimp
   palette regardless (see import_edited_sprites.py) -- but keep edges
   crisp: any soft/anti-aliased pixel you introduce will get rounded to
   whichever flat Wimp colour is nearest, which can look messier than
   if you'd just used a hard edge to begin with.
3. Keep the image's own pixel dimensions an EXACT multiple of 16x the
   original native size (i.e. don't crop or resize the canvas) --
   `import_edited_sprites.py` downscales by exactly 1/16 assuming this.
4. Preserve transparency (alpha channel) -- fully transparent stays
   background/outside-the-sprite; anything you want visible needs full
   (255) alpha. Partial/soft alpha edges get thresholded at import
   time, same as full opaque/transparent, so there's no benefit to
   soft-edged alpha either.
5. Save as PNG, overwriting the same `_16x.png` file in this folder.
6. Run `python3 assets/import_edited_sprites.py` from the repo root.
   This downscales each edited `_16x.png` back to native resolution
   (via majority-colour-per-16x16-block voting, robust to a few
   stray/rough pixels near a block edge), re-quantises against the
   fixed Wimp palette, and rebuilds `assets/PawnSprites`/
   `assets/!Sprites`/`assets/!Sprites22` directly from your edited
   artwork -- bypassing the original generate_icon_sprites.py/
   generate_app_icon.py Python-drawn designs entirely for whichever
   sprites you touched. Files you didn't edit are rebuilt unchanged
   from their own native PNGs, so it's safe to edit only some of them.
7. `make deploy` as normal to test in Arculator.

## If you want to start over from the programmatic design

Re-run `python3 assets/generate_icon_sprites.py` and/or
`python3 assets/generate_app_icon.py` (this regenerates the native
PNGs from scratch, overwriting any prior import), then
`python3 assets/export_sprites_for_editing.py` again to refresh this
folder's `_16x.png` files back to a clean baseline.

## Files in this folder

| Sprite | Native PNG | Edit this (16x) | Packed into | Sprite name(s) |
|---|---|---|---|---|
| Green pawn | `pawn0.png` | `pawn0_16x.png` | `assets/PawnSprites` | `pawn0` |
| Red pawn | `pawn1.png` | `pawn1_16x.png` | `assets/PawnSprites` | `pawn1` |
| Blue pawn | `pawn2.png` | `pawn2_16x.png` | `assets/PawnSprites` | `pawn2` |
| Yellow pawn | `pawn3.png` | `pawn3_16x.png` | `assets/PawnSprites` | `pawn3` |
| App icon, square, full | `archiludo_full_sq.png` | `archiludo_full_sq_16x.png` | `assets/!Sprites22` | `!archiludo` |
| App icon, square, half | `archiludo_half_sq.png` | `archiludo_half_sq_16x.png` | `assets/!Sprites22` | `sm!archiludo` |
| App icon, rect, full | `archiludo_full_rect.png` | `archiludo_full_rect_16x.png` | `assets/!Sprites` | `!archiludo` |
| App icon, rect, half | `archiludo_half_rect.png` | `archiludo_half_rect_16x.png` | `assets/!Sprites` | `sm!archiludo` |

The "rect" (rectangular-pixel, modes 12/15/39) app icon variants are
already vertically squished 2:1 relative to how they'll actually
display on screen -- edit them at their own native aspect ratio as
exported (don't un-squish them yourself), the squish is compensated
for by the screen mode's own non-square pixels, same as everywhere
else non-square art appears in this project (see CLAUDE.md's Testing
section).
"""


def main():
    EDIT_DIR.mkdir(exist_ok=True)

    for src, name in SPRITE_SOURCES:
        if not src.exists():
            print(f"skipping {name}: {src} not found -- run the relevant "
                  f"generate_*.py first", file=sys.stderr)
            continue
        img = Image.open(src).convert("RGBA")

        native_out = EDIT_DIR / f"{name}.png"
        img.save(native_out)

        big = img.resize((img.width * UPSCALE, img.height * UPSCALE), Image.NEAREST)
        big_out = EDIT_DIR / f"{name}_{UPSCALE}x.png"
        big.save(big_out)

        print(f"wrote {native_out} ({img.width}x{img.height}), "
              f"{big_out} ({big.width}x{big.height})")

    (EDIT_DIR / "README.md").write_text(README)
    print(f"wrote {EDIT_DIR / 'README.md'}")


if __name__ == "__main__":
    main()
