#!/usr/bin/env python3
"""
ArchiLudo sprite export-for-editing
======================================

Summary: Exports every sprite this project currently ships (the four
pawn colours, generate_icon_sprites.py; the four app-icon size/aspect
variants, generate_app_icon.py) as plain PNGs into assets/edit/, for
hand pixel-correction in an external image editor -- per explicit user
request ("save PNG versions... so i can try to pixel correct them").
See assets/import_edited_sprites.py to convert whatever ends up in
assets/edit/ back into the real packed RISC OS sprite files
(PawnSprite/!Sprites/!Sprites22) -- the two scripts are a matched
pair, see that one's own doc comment for the round-trip.

Why PNG, not PSD: Pillow (the only image library available in this
project's tooling) can only READ PSD files, not write them, and there's
no reliable pure-Python PSD writer to reach for instead. This isn't
much of a loss for sprites like these anyway -- each one is already a
single flat layer (solid colour regions + a hard alpha mask, no blend
modes/effects/multiple layers to preserve), which is exactly what PNG
represents natively. PNG is also the normal working format for pixel
art at this scale in practice, not a compromise.

One file per sprite, at its exact real native resolution (e.g. 26x26
for a pawn) -- edit this file directly, in place, at native size. Round
7.49 dropped the earlier round 7.42 approach of ALSO exporting a
16x-upscaled `_16x.png` "editing copy" (Image.NEAREST, so every source
pixel became a clean, individually-clickable 16x16 block) -- per
explicit user request, after the 16x round-trip's own indirection
turned out to be exactly what caused a real bug: a native-resolution
edit was silently ignored because import_edited_sprites.py preferred
the stale, unedited `_16x.png` sibling sitting next to it (see
docs/ARCHITECTURE.md's Round 7.49 for the full incident). Editing the
tiny native file directly needs a capable pixel-art editor with its own
precise zoom (Piskel, GIMP's Pencil tool, Aseprite -- see this folder's
own README.md for the recommendation and why plain MS Paint doesn't
work: it silently flattens the alpha channel, filling the transparent
background solid white, which is the OTHER real bug the same incident
surfaced), but removes the "two files, one of which can go stale and
silently win" footgun entirely.

Syntax:  python3 assets/export_sprites_for_editing.py
Output:  assets/edit/*.png (one native-resolution file per sprite),
         assets/edit/README.md
"""

import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
EDIT_DIR = HERE / "edit"

# (native PNG source, edit/ basename)
SPRITE_SOURCES = [
    (HERE / "pawn_icon0.png", "pawn0"),
    (HERE / "pawn_icon1.png", "pawn1"),
    (HERE / "pawn_icon2.png", "pawn2"),
    (HERE / "pawn_icon3.png", "pawn3"),
    (HERE / "app_icon_full.png", "archiludo_full_sq"),
    (HERE / "app_icon_half.png", "archiludo_half_sq"),
    (HERE / "app_icon_full_rect.png", "archiludo_full_rect"),
    (HERE / "app_icon_half_rect.png", "archiludo_half_rect"),
]

README = """\
# ArchiLudo sprite pixel-editing workspace

Generated by `assets/export_sprites_for_editing.py`. Edit these PNGs
directly, in place, at their real native resolution (e.g. 26x26 for a
pawn) -- then run `assets/import_edited_sprites.py` to convert your
edits back into the real sprite files ArchiLudo actually ships.

Round 7.49: this used to also export a 16x-upscaled `_16x.png` "editing
copy" of each sprite, meant to be edited instead of the native file.
That indirection caused a real bug -- a native-resolution edit was
silently ignored because the import step preferred the stale, unedited
`_16x.png` sitting next to it -- so it's gone; edit the native file
directly, in place, with no second copy to go stale.

## Workflow

1. Open a native PNG (e.g. `pawn0.png`) in a real pixel-art editor --
   **not** MS Paint (see "Editor recommendation" below). Zoom your
   editor's own view in as far as you need; there's no baked-in 16x
   copy to lean on any more.
2. Edit using a **1px hard-edged pencil tool only** -- never a soft or
   anti-aliased brush, and never resize/rotate/apply filters. Colours
   don't need to be exact matches to the originals -- the import step
   re-quantises everything against RISC OS's fixed 16-colour Wimp
   palette regardless (see import_edited_sprites.py) -- but keep edges
   crisp: any soft/anti-aliased pixel you introduce gets rounded to
   whichever flat Wimp colour is nearest, which can look messier than
   if you'd just used a hard edge to begin with.
3. Don't crop or resize the canvas -- keep the image's own pixel
   dimensions exactly as exported.
4. Preserve transparency (alpha channel) -- fully transparent stays
   background/outside-the-sprite; anything you want visible needs full
   (255) alpha. Partial/soft alpha edges get thresholded at import
   time, same as full opaque/transparent, so there's no benefit to
   soft-edged alpha either. **Check your editor actually preserves
   alpha on save** -- this is exactly what tripped up the round 7.49
   incident (see above): MS Paint silently flattens transparency,
   filling the background solid white instead.
5. Save as PNG, overwriting the same file in this folder.
6. Run `python3 assets/import_edited_sprites.py` from the repo root.
   This re-quantises your edit against the fixed Wimp palette and
   rebuilds `assets/PawnSprite`/`assets/!Sprites`/`assets/!Sprites22`
   directly from it -- bypassing the original generate_icon_sprites.py/
   generate_app_icon.py Python-drawn designs entirely for whichever
   sprites you touched. Files you didn't edit are rebuilt unchanged
   from their own native PNGs, so it's safe to edit only some of them.
7. `make deploy` as normal to test in Arculator.

## Editor recommendation

**Not MS Paint** -- classic Paint has no real alpha-channel support at
all: it silently flattens any transparency to solid white on open/save,
and doesn't offer a genuinely hard-edged 1px pencil in every tool mode
either. Both of those are exactly what caused the round 7.49 incident.

- **[Piskel](https://www.piskelapp.com/)** (free, web or downloadable)
  -- purpose-built for pixel art: hard-edged pencil by default (nothing
  to accidentally set to anti-aliased), transparency is a first-class
  citizen, zoomed pixel grid built in. Best fit for this workflow.
- **GIMP** (free) works too, with care: use the **Pencil** tool (not
  Paintbrush, which is soft/anti-aliased), make sure the layer has an
  alpha channel (`Layer -> Transparency -> Add Alpha Channel`), and
  export as PNG normally -- GIMP preserves alpha correctly.
- **Aseprite** (small one-time fee, ~$20) if you want the professional
  dedicated pixel-art tool -- probably overkill for occasional sprite
  tweaks.

## If you want to start over from the programmatic design

Re-run `python3 assets/generate_icon_sprites.py` and/or
`python3 assets/generate_app_icon.py` (this regenerates the native
PNGs from scratch, overwriting any prior import), then
`python3 assets/export_sprites_for_editing.py` again to refresh this
folder back to a clean baseline.

## Files in this folder

| Sprite | Edit this | Packed into | Sprite name(s) |
|---|---|---|---|
| Green pawn | `pawn0.png` | `assets/PawnSprite` | `pawn0` |
| Red pawn | `pawn1.png` | `assets/PawnSprite` | `pawn1` |
| Blue pawn | `pawn2.png` | `assets/PawnSprite` | `pawn2` |
| Yellow pawn | `pawn3.png` | `assets/PawnSprite` | `pawn3` |
| App icon, square, full | `archiludo_full_sq.png` | `assets/!Sprites22` | `!archiludo` |
| App icon, square, half | `archiludo_half_sq.png` | `assets/!Sprites22` | `sm!archiludo` |
| App icon, rect, full | `archiludo_full_rect.png` | `assets/!Sprites` | `!archiludo` |
| App icon, rect, half | `archiludo_half_rect.png` | `assets/!Sprites` | `sm!archiludo` |

The "rect" (rectangular-pixel, modes 12/15/39) app icon variants are
already vertically squished 2:1 relative to how they'll actually
display on screen -- edit them at their own native aspect ratio as
exported (don't un-squish them yourself), the squish is compensated
for by the screen mode's own non-square pixels, same as everywhere
else non-square art appears in this project (see CLAUDE.md's Testing
section).
"""


def main():
    EDIT_DIR.mkdir(exist_ok=True)

    for src, name in SPRITE_SOURCES:
        if not src.exists():
            print(f"skipping {name}: {src} not found -- run the relevant "
                  f"generate_*.py first", file=sys.stderr)
            continue
        img = Image.open(src).convert("RGBA")

        native_out = EDIT_DIR / f"{name}.png"
        img.save(native_out)

        print(f"wrote {native_out} ({img.width}x{img.height})")

    (EDIT_DIR / "README.md").write_text(README)
    print(f"wrote {EDIT_DIR / 'README.md'}")


if __name__ == "__main__":
    main()
